### ISSUE TITLE
Missing < and > keys

### ISSUE THREAD

**Issue by jirgn** [noahfrederick/dots#6]
Hello there,

I just got my new planck keyboard from massdrop, and wanted to try your layout, wright when i saw it. 
But after installing, i wondered how to type < and > keys. These are described on your website, but are not part of your current configuration.
Just fiddled around with the code and did a minor patch on my side (https://github.com/jirgn/.dotfiles/commit/57aa4e790632f8ec5642be1f02ed2260fd1f234f)

I just wanted to know if I am right with the assumption that the keys are not present, because these are essential when coding, and i can not believe you missed this.

**Comment by noahfrederick** [comment]
Hello. In a standard US keyboard layout `<` and `>` are produced by <kbd>Shift</kbd>+<kbd>,</kbd> and <kbd>Shift</kbd>+<kbd>.</kbd> respectively, which is how I type those symbols.

**Comment by jirgn** [comment]
(facepalm) -- sorry for this one
